# Desktop workstation: gaming, NVIDIA GPU, ethernet.
{ ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./local-packages.nix
    ../common-host-info.nix
    ../../nixos/modules
    ./modules
  ];

  mySystem = {
    hostProfile = "desktop";
    waydroid.enable = false;
    flatpak.enable = false;
    kdeconnect.enable = false; # Desktop has no Bluetooth adapter; avoids repetitive Bluez warnings.
    i2pd.enable = true;
    yggdrasil.enable = true;
    netdata.enable = true;
    vnc.enable = true;
  };

  # LUKS unlock for swap partition — separate from hardware-configuration.nix because
  # the root LUKS device was auto-generated by nixos-generate-config, while the swap
  # LUKS device was added manually from the original installer's configuration.nix.
  boot.initrd.luks.devices."luks-4e98b5c2-4022-41a6-8e97-dddf0fe5c408".device =
    "/dev/disk/by-uuid/4e98b5c2-4022-41a6-8e97-dddf0fe5c408";

  services.avahi.allowInterfaces = [ "eno1" ];
}
