# Allow and deny command/file patterns for Claude Code permissions.
{
  allow = [
    "Bash(git *)"
    "Bash(gh *)"
    "Bash(npm run *)"
    "Bash(npx *)"
    "Bash(pnpm *)"
    "Bash(bun *)"
    "Bash(just *)"
    "Bash(make *)"
    "Bash(cmake *)"
    "Bash(nix *)"
    "Bash(nh *)"
    "Bash(home-manager *)"
    "Bash(cargo *)"
    "Bash(rustfmt *)"
    "Bash(go *)"
    "Bash(gofmt *)"
    "Bash(zig *)"
    "Bash(python *)"
    "Bash(pip *)"
    "Bash(uv *)"
    "Bash(ruff *)"
    "Bash(biome *)"
    "Bash(prettier *)"
    "Bash(statix *)"
    "Bash(deadnix *)"
    "Bash(docker *)"
    "Bash(docker-compose *)"
    "Bash(systemctl --user *)"
    "Bash(tmux *)"
  ];

  deny = [
    "Bash(rm -rf /)"
    "Bash(rm -rf ~)"
    "Bash(rm -rf /*)"
    "Bash(> /dev/sda*)"
    "Bash(mkfs*)"
    "Bash(dd if=*)"
    "Read(.env)"
    "Read(.env.*)"
    "Read(./secrets/**)"
    "Read(.ssh/*)"
    "Read(**/id_rsa*)"
    "Read(**/id_ed25519*)"
  ];
}
