# PRIVACY NOTE: Filesystem UUIDs are unique hardware identifiers. If this repo becomes
# public, these can fingerprint specific hardware in forensic analysis. Consider using
# disk labels instead of UUIDs or adding this file to .gitignore.
# TODO: Implement full disk encryption (LUKS) for root partition — requires reinstallation.
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ config, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "nvme"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "usb_storage" ]; # On-demand, not needed in initrd
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/575267d8-6156-47f6-b808-e009ff2d0942";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/068C-6C4F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Disk swap disabled — zram swap configured in nixos/modules/security/opsec.nix
  swapDevices = [ ];

  # NetworkManager handles networking
  nixpkgs.hostPlatform = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;
}
