# Zsh shell aliases.

{
  constants,
  ...
}:

{
  programs.zsh.shellAliases =
    let
      inherit (constants) editor;
      nixTemplates = "git+https://codeberg.org/yztr/nixos?ref=main&dir=dev-shells#";
      commitSplitPrompt = "Review all current git changes, propose a commit plan that splits work into minimal logical commits, then execute it commit-by-commit using signed commits (git commit -S). For each commit, stage only relevant hunks/files, run relevant checks for touched files, and use a clear conventional commit message. Show the plan before creating the first commit.";
      refactorMaintainabilityPrompt = "Analyze this repository and perform a maintainability-focused refactor with zero behavior regressions. Detect the active languages, frameworks, and conventions first, then identify duplicated logic, oversized files/functions, mixed responsibilities, weak module boundaries, dead code, and non-idiomatic patterns for each language. Create a prioritized plan by impact and risk with concrete file-level actions before editing. Implement changes in small atomic steps that preserve external behavior and public APIs unless a migration is explicitly required. Split code into coherent modules where responsibilities are mixed, extract reusable utilities only when duplication is real, and align naming, structure, error handling, and testing patterns with project conventions for each tech stack. Remove bad practices and generic boilerplate, avoid broad rewrites, and avoid placeholder TODO solutions. After each step run relevant formatter, linter, type-check, and tests for touched files and fix all findings. Finish with a concise report of what was split, what duplication was removed, what remains risky, and the next highest-value refactors.";
      securityAuditPrompt = "Perform a comprehensive security audit for this repository with evidence-based findings only. First detect languages, frameworks, runtimes, dependency managers, deployment files, and trust boundaries. Build a threat model that covers authentication and authorization, input validation, injection risks, command execution, SSRF, path traversal, XSS, CSRF, open redirects, unsafe deserialization, insecure cryptography, secret leakage, dependency and supply-chain risk, CI and CD hardening, container and IaC misconfiguration, and least-privilege violations. Review code, configs, scripts, and docs; report concrete vulnerabilities with severity, exploitability, impact, and exact file paths and lines. Prioritize critical and high findings, then medium and low. For each finding propose minimal idiomatic fixes that match the project stack and include verification steps and tests. Avoid generic advice and avoid speculative findings without repository evidence. Preserve behavior unless an explicit fix requires a controlled change. Finish with a remediation plan ordered by risk, quick wins, and long-term hardening tasks.";
      markdownSyncPrompt = "Audit project documentation for accuracy and freshness, then update it to match the current repository state. Focus on README.md, AGENTS.md files, and all markdown under docs and module directories. Verify every documented command, workflow, path, option, feature, dependency, and architecture claim against real code, scripts, flake outputs, module imports, and current project structure. Flag and fix outdated, ambiguous, or contradictory statements. Remove stale references, missing steps, and copy paste drift. Ensure instructions are actionable, deterministic, and aligned with current tooling and conventions by language and framework. Keep edits precise and minimal while improving clarity and maintainability. Prefer concrete paths and exact command examples. Preserve intentional project specific guidance and scope rules from AGENTS files. At the end, summarize what changed, what was verified, and any remaining documentation gaps that still require human decisions.";
    in
    {
      # Agent-safe defaults (agents expect standard stdout)
      cat = "cat";
      ls = "ls --color=auto";

      # Human-friendly tool aliases (ll, la, lt auto-generated by eza module)
      c = "bat --style=auto";
      l = "eza --icons --group-directories-first";

      # Agent context tools (e.g. "ctx | wl-copy" to paste into AI)
      ctx = "eza --tree --level=2 --ignore-glob='.git|node_modules|.direnv|target|dist|.next'";
      rmap = "git ls-files";

      # Navigation
      ".." = "cd ..";
      "..." = "cd ../..";
      "...." = "cd ../../..";
      "....." = "cd ../../../..";
      dl = "cd ~/Downloads";
      dt = "cd ~/Desktop";
      docs = "cd ~/Documents";
      ci = "zi";

      # Search and text
      less = "bat --style=auto --paging=always";
      rgi = "rg -i";
      rgf = "rg --files-with-matches";
      rgc = "rg --count";
      tk = "tokei";
      tf = "tokei --files";
      fs = "fselect";

      # Editors
      v = "${editor}";
      se = "sudoedit";
      open = "xdg-open";
      ezshr = "${editor} ~/System/home-manager/modules/terminal/zsh";
      enix = "${editor} ~/System";

      # System info
      ff = "fastfetch";
      mf = "microfetch";
      of = "onefetch";

      # AI tools
      occm = "opencode_glm --prompt '${commitSplitPrompt}'"; # OpenCode Sonnet commit-splitting + signed-commit workflow.
      clcm = "claude --dangerously-skip-permissions '${commitSplitPrompt}'"; # Claude commit-splitting + signed-commit workflow.
      cxcm = "command codex --no-alt-screen --dangerously-bypass-approvals-and-sandbox '${commitSplitPrompt}'"; # Codex commit-splitting + signed-commit workflow.
      ocrf = "opencode_glm --prompt '${refactorMaintainabilityPrompt}'"; # OpenCode Sonnet maintainability refactor workflow.
      clrf = "claude --dangerously-skip-permissions '${refactorMaintainabilityPrompt}'"; # Claude maintainability refactor workflow.
      cxrf = "command codex --no-alt-screen --dangerously-bypass-approvals-and-sandbox '${refactorMaintainabilityPrompt}'"; # Codex maintainability refactor workflow.
      ocsa = "opencode_glm --prompt '${securityAuditPrompt}'"; # OpenCode Sonnet security audit workflow.
      clsa = "claude --dangerously-skip-permissions '${securityAuditPrompt}'"; # Claude security audit workflow.
      cxsa = "command codex --no-alt-screen --dangerously-bypass-approvals-and-sandbox '${securityAuditPrompt}'"; # Codex security audit workflow.
      ocmd = "opencode_glm --prompt '${markdownSyncPrompt}'"; # OpenCode Sonnet markdown documentation audit workflow.
      clmd = "claude --dangerously-skip-permissions '${markdownSyncPrompt}'"; # Claude markdown documentation audit workflow.
      cxmd = "command codex --no-alt-screen --dangerously-bypass-approvals-and-sandbox '${markdownSyncPrompt}'"; # Codex markdown documentation audit workflow.

      cl = "claude --dangerously-skip-permissions"; # Claude Code YOLO (default).
      clglm = "claude_glm"; # Claude via GLM-backed ZAI endpoint wrapper (includes YOLO).

      gem = "gemini --yolo"; # Gemini CLI YOLO (default).

      oc = "opencode"; # Launch OpenCode interactive session.
      ocglm = "opencode_glm"; # OpenCode using GLM profile config.
      ocgem = "opencode_gemini"; # OpenCode using Gemini profile config.
      ocgpt = "opencode_gpt"; # OpenCode using GPT profile config.
      ocs = "opencode_sonnet"; # OpenCode using Sonnet-only profile config.
      ocf = "opencode --continue --fork"; # Continue OpenCode session in a forked branch.
      ocrun = "opencode run"; # Non-interactive OpenCode run.

      cx = "command codex --no-alt-screen --dangerously-bypass-approvals-and-sandbox"; # Codex YOLO (default).

      # Gastown (multi-agent orchestrator)
      gti = "gt install ~/gt --git"; # Initialize town workspace (one-time).
      gtra = "gt rig add"; # Add a rig (gt rig add <name> <url> or --adopt).
      gtca = "gt crew add"; # Create crew workspace (gt crew add <name> --rig <rig>).
      gts = "gt status"; # Town overview: rigs, agents, state.
      gtf = "gt feed"; # TUI live feed of agent activity.
      gtd = "gt dashboard"; # Web dashboard for monitoring.
      gtma = "gt mayor attach"; # Attach to the Mayor coordinator.
      gtrl = "gt rig list"; # List all registered rigs.
      gtwl = "gt worker list"; # List active polecat workers.
      gtcl = "gt convoy list"; # List active work convoys.
      gtbl = "gt bead list"; # List all work items (beads).
      gtl = "gt log"; # Agent activity log.

      # Nix
      ns = "nix-shell";
      nd = "nix develop --command zsh";
      nfu = "nix flake update";
      nfs = "nix flake show";
      nfi = "nix flake init";

      # Dev environment templates
      nfib = "nfi -t '${nixTemplates}bun'";
      nfid = "nfi -t '${nixTemplates}deno'";
      nfin = "nfi -t '${nixTemplates}nodejs'";
      nfip = "nfi -t '${nixTemplates}python-venv'";
      nfirs = "nfi -t '${nixTemplates}rust-stable'";
      nfirn = "nfi -t '${nixTemplates}rust-nightly'";

      # System reports
      sr = "sudo system-report full";
      sre = "sudo system-report errors";
      srv = "system-report view";
      srve = "system-report view-errors";

      # Systemd
      sc = "systemctl";
      scu = "systemctl --user";
      scs = "systemctl status";
      scr = "sudo systemctl restart";
      reboot = "sudo reboot";
      shutdown = "sudo shutdown now";

      # Process management
      psg = "ps aux | grep";
      killall = "pkill -f";

      # Network
      ssh = "TERM=xterm-256color command ssh";
      ports = "lsof -i -P -n | grep LISTEN";
      myip = "curl -s https://am.i.mullvad.net/ip"; # Privacy-respecting IP check
      localip = "ip route get 1.1.1.1 | awk '{print $7}'";

      # Disk usage
      du1 = "du -h --max-depth=1";
      ducks = "du -cks * | sort -rn | head";

      # Clipboard (Wayland)
      pbcopy = "wl-copy";
      pbpaste = "wl-paste";

      # Docker
      d = "docker";
      dc = "docker-compose";
      dps = "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'";
      dpa = "docker ps -a --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'";
      di = "docker images --format 'table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}'";
      dex = "docker exec -it";
      dlogs = "docker logs -f";

      gpu-fans = "nvidia-fans";

      # Safety nets
      rm = "rm -I";
      mv = "mv -i";
      cp = "cp -i";

      j = "just";
    };
}
