# Zsh shell aliases.

{
  constants,
  ...
}:

{
  programs.zsh.shellAliases =
    let
      inherit (constants) editor;
      nixTemplates = "github:82163/nixos-config/main?dir=devShells#";
    in
    {
      # Agent-safe defaults (agents expect standard stdout)
      cat = "cat";
      ls = "ls --color=auto";

      # Human-friendly tool aliases (ll, la, lt auto-generated by eza module)
      c = "bat --style=auto";
      l = "eza --icons --group-directories-first";

      # Agent context tools (e.g. "ctx | wl-copy" to paste into AI)
      ctx = "eza --tree --level=2 --ignore-glob='.git|node_modules|.direnv|target|dist|.next'";
      rmap = "git ls-files";

      # Navigation
      ".." = "cd ..";
      "..." = "cd ../..";
      "...." = "cd ../../..";
      "....." = "cd ../../../..";
      dl = "cd ~/Downloads";
      dt = "cd ~/Desktop";
      docs = "cd ~/Documents";
      ci = "zi";

      # Search and text
      less = "bat --style=auto --paging=always";
      rgi = "rg -i";
      rgf = "rg --files-with-matches";
      rgc = "rg --count";
      tk = "tokei";
      tf = "tokei --files";
      fs = "fselect";

      # Editors
      v = "${editor}";
      se = "sudoedit";
      open = "xdg-open";
      ezshr = "${editor} ~/System/home-manager/modules/terminal/zsh";
      enix = "${editor} ~/System";

      # System info
      ff = "fastfetch";
      mf = "microfetch";
      of = "onefetch";

      # AI tools
      cl = "claude";
      oc = "opencode";
      "ac" = "ai-commit";
      "ak" = "ai-ask";
      "ah" = "ai-help";
      rmx = "repomix";
      "rmx-clip" = "repomix --copy"; # Bundle repo to clipboard for AI context
      gprai = "claude 'Create a PR for my current changes. Use gh pr create.'";
      grai = "claude 'Review my staged changes. Be concise.'";

      # Nix
      ns = "nix-shell";
      nd = "nix develop --command zsh";
      nfu = "nix flake update";
      nfs = "nix flake show";
      nfi = "nix flake init";

      # Dev environment templates
      nfib = "nfi -t '${nixTemplates}bun'";
      nfid = "nfi -t '${nixTemplates}deno'";
      nfin = "nfi -t '${nixTemplates}nodejs'";
      nfip = "nfi -t '${nixTemplates}python-venv'";
      nfirs = "nfi -t '${nixTemplates}rust-stable'";
      nfirn = "nfi -t '${nixTemplates}rust-nightly'";

      # System reports
      sr = "sudo system-report full";
      sre = "sudo system-report errors";
      srv = "system-report view";
      srve = "system-report view-errors";

      # Systemd
      sc = "systemctl";
      scu = "systemctl --user";
      scs = "systemctl status";
      scr = "sudo systemctl restart";
      reboot = "sudo reboot";
      shutdown = "sudo shutdown now";

      # Process management
      psg = "ps aux | grep";
      killall = "pkill -f";

      # Network
      ports = "lsof -i -P -n | grep LISTEN";
      myip = "curl -s https://am.i.mullvad.net/ip"; # Privacy-respecting IP check
      localip = "ip route get 1.1.1.1 | awk '{print $7}'";

      # Disk usage
      du1 = "du -h --max-depth=1";
      ducks = "du -cks * | sort -rn | head";

      # Clipboard (Wayland)
      pbcopy = "wl-copy";
      pbpaste = "wl-paste";

      # Docker
      d = "docker";
      dc = "docker-compose";
      dps = "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'";
      dpa = "docker ps -a --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'";
      di = "docker images --format 'table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}'";
      dex = "docker exec -it";
      dlogs = "docker logs -f";

      gpu-fans = "nvidia-fans";

      # Safety nets
      rm = "rm -I";
      mv = "mv -i";
      cp = "cp -i";

      j = "just";
    };
}
