# Workflow prompt constants used by AI agent shell aliases.
{
  commitSplit = "Review all current git changes, propose a commit plan that splits work into minimal logical commits, then execute it commit-by-commit using signed commits (git commit -S). For each commit, stage only relevant hunks/files, run relevant checks for touched files, and use a clear conventional commit message. Show the plan before creating the first commit.";

  refactorMaintainability = "Analyze this repository and perform a maintainability-focused refactor with zero behavior regressions. Detect the active languages, frameworks, and conventions first, then identify duplicated logic, oversized files/functions, mixed responsibilities, weak module boundaries, dead code, and non-idiomatic patterns for each language. Create a prioritized plan by impact and risk with concrete file-level actions before editing. Implement changes in small atomic steps that preserve external behavior and public APIs unless a migration is explicitly required. Split code into coherent modules where responsibilities are mixed, extract reusable utilities only when duplication is real, and align naming, structure, error handling, and testing patterns with project conventions for each tech stack. Remove bad practices and generic boilerplate, avoid broad rewrites, and avoid placeholder TODO solutions. After each step run relevant formatter, linter, type-check, and tests for touched files and fix all findings. Finish with a concise report of what was split, what duplication was removed, what remains risky, and the next highest-value refactors.";

  securityAudit = "Perform a comprehensive security audit for this repository with evidence-based findings only. First detect languages, frameworks, runtimes, dependency managers, deployment files, and trust boundaries. Build a threat model that covers authentication and authorization, input validation, injection risks, command execution, SSRF, path traversal, XSS, CSRF, open redirects, unsafe deserialization, insecure cryptography, secret leakage, dependency and supply-chain risk, CI and CD hardening, container and IaC misconfiguration, and least-privilege violations. Review code, configs, scripts, and docs; report concrete vulnerabilities with severity, exploitability, impact, and exact file paths and lines. Prioritize critical and high findings, then medium and low. For each finding propose minimal idiomatic fixes that match the project stack and include verification steps and tests. Avoid generic advice and avoid speculative findings without repository evidence. Preserve behavior unless an explicit fix requires a controlled change. Finish with a remediation plan ordered by risk, quick wins, and long-term hardening tasks.";

  markdownSync = "Audit project documentation for accuracy and freshness, then update it to match the current repository state. Focus on README.md, AGENTS.md files, and all markdown under docs and module directories. Verify every documented command, workflow, path, option, feature, dependency, and architecture claim against real code, scripts, module imports, and current project structure. Flag and fix outdated, ambiguous, or contradictory statements. Remove stale references, missing steps, and copy paste drift. Ensure instructions are actionable, deterministic, and aligned with current tooling and conventions by language and framework. Keep edits precise and minimal while improving clarity and maintainability. Prefer concrete paths and exact command examples. Preserve intentional project specific guidance and scope rules from AGENTS files. At the end, summarize what changed, what was verified, and any remaining documentation gaps that still require human decisions.";
}
