# Workflow prompt constants used by AI agent shell aliases.

{
  commitSplit = "Objective: transform current working tree into a minimal set of signed logical commits with zero unrelated changes. Workflow: 1) inspect git status, full diff, staged diff, and recent log style; 2) draft a commit plan with ordered commit scopes and rationale; 3) for each commit stage only relevant hunks and files, run targeted validation for touched files, then create signed commit with conventional message focused on intent; 4) re-run git status after each commit and continue until plan complete. Hard rules: never use git add ., never mix unrelated concerns, never commit secrets or generated noise, never rewrite history unless explicitly required. Output contract: show planned commit list before first commit, then report each created commit hash, message, and validation evidence.";

  refactorMaintainability = "Goal: increase maintainability with zero behavior drift. Sequence: discover stack conventions and module boundaries first; run baseline diagnostics; identify highest impact issues only (real duplication, oversized units, mixed responsibilities, weak boundaries, dead paths, non idiomatic constructs); produce a ranked file-level plan with risk and expected payoff before edits; implement in atomic steps that preserve APIs and behavior unless migration is explicitly required; validate after each step with formatter, lint, typecheck, and relevant tests; fix regressions immediately before next step. Hard rules: no broad rewrites, no speculative abstractions, no placeholder TODO fixes, no style churn without payoff, no hidden breaking changes. Completion criteria: all touched code passes checks, architecture boundaries are clearer, duplication reductions are concrete, and final report maps each change to maintainability gain and residual risk.";

  securityAudit = "Run a code and configuration security audit with evidence only. Process: inventory runtimes, frameworks, dependencies, entrypoints, secrets flow, and trust boundaries; build threat model per surface (authz and authn, input handling, injection classes, command execution, SSRF, path traversal, XSS, CSRF, redirects, deserialization, crypto misuse, secret exposure, supply chain, CI CD, container and IaC posture, privilege boundaries); inspect code, scripts, configs, and docs for concrete issues. Reporting format for each finding: severity, exploitability, impact, exact path and line, proof from repository evidence, minimal stack-native fix, and verification command. Hard rules: no speculative claims, no duplicate findings, no generic checklist filler, no behavior changing fix without stating risk. Deliverables: prioritized remediation backlog (critical to low), quick wins, and long range hardening tasks with owner-ready action wording.";

  buildPerformance = "Run a build and performance bottleneck pass with measurable evidence. Sequence: detect project build and test entrypoints from repository config; capture baseline timings for the relevant build and critical checks; identify top bottlenecks in build graph, dependency churn, cache misses, or slow test targets; apply minimal low risk optimizations that match existing stack conventions; rerun the same commands to capture after metrics; report deltas with absolute time and percent change. Hard rules: no risky architectural rewrites, no speculative tuning without measurement, no hidden behavior changes, no skipping required validation checks. Output contract: include baseline command set, optimization actions, after metrics, and prioritized next optimizations by expected ROI.";

  markdownSync = "Synchronize markdown docs with actual repository behavior. Scope: README.md, AGENTS.md files, guides, and docs directories. Method: verify every command, path, option, workflow, architecture claim, and dependency statement against current code, scripts, imports, and configuration; fix drift, contradictions, stale references, and ambiguous steps; keep edits minimal but decisive; preserve project specific constraints from AGENTS guidance; prefer deterministic commands and concrete paths over narrative text. Hard rules: do not invent capabilities, do not keep unverifiable claims, do not rewrite style without accuracy gain. Completion output: list files updated, facts verified, commands revalidated, and unresolved doc gaps that require explicit human decisions.";
}
